/*
Couchbase Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// Couchbase, Inc. licenses this to you under the Apache License, Version 2.0 (the “License”);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at https://www.apache.org/licenses/LICENSE-2.0.

// Unless required by applicable law or agreed to in writing, software distributed under the License
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and limitations under the License.

package couchbasecapella

import (
	"encoding/json"
)

// DeleteAllowListEntryRequest struct for DeleteAllowListEntryRequest
type DeleteAllowListEntryRequest struct {
	CidrBlock string `json:"cidrBlock"`
}

// NewDeleteAllowListEntryRequest instantiates a new DeleteAllowListEntryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteAllowListEntryRequest(cidrBlock string) *DeleteAllowListEntryRequest {
	this := DeleteAllowListEntryRequest{}
	this.CidrBlock = cidrBlock
	return &this
}

// NewDeleteAllowListEntryRequestWithDefaults instantiates a new DeleteAllowListEntryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteAllowListEntryRequestWithDefaults() *DeleteAllowListEntryRequest {
	this := DeleteAllowListEntryRequest{}
	return &this
}

// GetCidrBlock returns the CidrBlock field value
func (o *DeleteAllowListEntryRequest) GetCidrBlock() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CidrBlock
}

// GetCidrBlockOk returns a tuple with the CidrBlock field value
// and a boolean to check if the value has been set.
func (o *DeleteAllowListEntryRequest) GetCidrBlockOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CidrBlock, true
}

// SetCidrBlock sets field value
func (o *DeleteAllowListEntryRequest) SetCidrBlock(v string) {
	o.CidrBlock = v
}

func (o DeleteAllowListEntryRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["cidrBlock"] = o.CidrBlock
	}
	return json.Marshal(toSerialize)
}

type NullableDeleteAllowListEntryRequest struct {
	value *DeleteAllowListEntryRequest
	isSet bool
}

func (v NullableDeleteAllowListEntryRequest) Get() *DeleteAllowListEntryRequest {
	return v.value
}

func (v *NullableDeleteAllowListEntryRequest) Set(val *DeleteAllowListEntryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteAllowListEntryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteAllowListEntryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteAllowListEntryRequest(val *DeleteAllowListEntryRequest) *NullableDeleteAllowListEntryRequest {
	return &NullableDeleteAllowListEntryRequest{value: val, isSet: true}
}

func (v NullableDeleteAllowListEntryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteAllowListEntryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
