/*
Couchbase Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// Couchbase, Inc. licenses this to you under the Apache License, Version 2.0 (the “License”);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at https://www.apache.org/licenses/LICENSE-2.0.

// Unless required by applicable law or agreed to in writing, software distributed under the License
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and limitations under the License.

package couchbasecapella

import (
	"encoding/json"
)

// StatusOK struct for StatusOK
type StatusOK struct {
	Status string `json:"status"`
}

// NewStatusOK instantiates a new StatusOK object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatusOK(status string) *StatusOK {
	this := StatusOK{}
	this.Status = status
	return &this
}

// NewStatusOKWithDefaults instantiates a new StatusOK object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatusOKWithDefaults() *StatusOK {
	this := StatusOK{}
	return &this
}

// GetStatus returns the Status field value
func (o *StatusOK) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *StatusOK) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *StatusOK) SetStatus(v string) {
	o.Status = v
}

func (o StatusOK) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableStatusOK struct {
	value *StatusOK
	isSet bool
}

func (v NullableStatusOK) Get() *StatusOK {
	return v.value
}

func (v *NullableStatusOK) Set(val *StatusOK) {
	v.value = val
	v.isSet = true
}

func (v NullableStatusOK) IsSet() bool {
	return v.isSet
}

func (v *NullableStatusOK) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatusOK(val *StatusOK) *NullableStatusOK {
	return &NullableStatusOK{value: val, isSet: true}
}

func (v NullableStatusOK) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatusOK) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
