/*
Couchbase Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// Couchbase, Inc. licenses this to you under the Apache License, Version 2.0 (the “License”);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at https://www.apache.org/licenses/LICENSE-2.0.

// Unless required by applicable law or agreed to in writing, software distributed under the License
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and limitations under the License.

package couchbasecapella

import (
	"encoding/json"
)

// V3ClusterStatusResponse struct for V3ClusterStatusResponse
type V3ClusterStatusResponse struct {
	Status V3ClusterStatus `json:"status"`
}

// NewV3ClusterStatusResponse instantiates a new V3ClusterStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV3ClusterStatusResponse(status V3ClusterStatus) *V3ClusterStatusResponse {
	this := V3ClusterStatusResponse{}
	this.Status = status
	return &this
}

// NewV3ClusterStatusResponseWithDefaults instantiates a new V3ClusterStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV3ClusterStatusResponseWithDefaults() *V3ClusterStatusResponse {
	this := V3ClusterStatusResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *V3ClusterStatusResponse) GetStatus() V3ClusterStatus {
	if o == nil {
		var ret V3ClusterStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *V3ClusterStatusResponse) GetStatusOk() (*V3ClusterStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *V3ClusterStatusResponse) SetStatus(v V3ClusterStatus) {
	o.Status = v
}

func (o V3ClusterStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableV3ClusterStatusResponse struct {
	value *V3ClusterStatusResponse
	isSet bool
}

func (v NullableV3ClusterStatusResponse) Get() *V3ClusterStatusResponse {
	return v.value
}

func (v *NullableV3ClusterStatusResponse) Set(val *V3ClusterStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV3ClusterStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV3ClusterStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV3ClusterStatusResponse(val *V3ClusterStatusResponse) *NullableV3ClusterStatusResponse {
	return &NullableV3ClusterStatusResponse{value: val, isSet: true}
}

func (v NullableV3ClusterStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV3ClusterStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
