/*
Couchbase Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// Couchbase, Inc. licenses this to you under the Apache License, Version 2.0 (the “License”);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at https://www.apache.org/licenses/LICENSE-2.0.

// Unless required by applicable law or agreed to in writing, software distributed under the License
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and limitations under the License.

package couchbasecapella

import (
	"encoding/json"
	"fmt"
)

// V3Environment the model 'V3Environment'
type V3Environment string

// List of v3Environment
const (
	HOSTED V3Environment = "hosted"
	VPC    V3Environment = "vpc"
)

var allowedV3EnvironmentEnumValues = []V3Environment{
	"hosted",
	"vpc",
}

func (v *V3Environment) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V3Environment(value)
	for _, existing := range allowedV3EnvironmentEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V3Environment", value)
}

// NewV3EnvironmentFromValue returns a pointer to a valid V3Environment
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV3EnvironmentFromValue(v string) (*V3Environment, error) {
	ev := V3Environment(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V3Environment: valid values are %v", v, allowedV3EnvironmentEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V3Environment) IsValid() bool {
	for _, existing := range allowedV3EnvironmentEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v3Environment value
func (v V3Environment) Ptr() *V3Environment {
	return &v
}

type NullableV3Environment struct {
	value *V3Environment
	isSet bool
}

func (v NullableV3Environment) Get() *V3Environment {
	return v.value
}

func (v *NullableV3Environment) Set(val *V3Environment) {
	v.value = val
	v.isSet = true
}

func (v NullableV3Environment) IsSet() bool {
	return v.isSet
}

func (v *NullableV3Environment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV3Environment(val *V3Environment) *NullableV3Environment {
	return &NullableV3Environment{value: val, isSet: true}
}

func (v NullableV3Environment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV3Environment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
