/*
Couchbase Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// Couchbase, Inc. licenses this to you under the Apache License, Version 2.0 (the “License”);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at https://www.apache.org/licenses/LICENSE-2.0.

// Unless required by applicable law or agreed to in writing, software distributed under the License
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and limitations under the License.

package couchbasecapella

import (
	"encoding/json"
	"fmt"
)

// V3ClusterStatus the model 'V3ClusterStatus'
type V3ClusterStatus string

// List of v3ClusterStatus
const (
	V3_DRAFT      V3ClusterStatus = "draft"
	V3_DEPLOYING  V3ClusterStatus = "deploying"
	V3_DESTROYING V3ClusterStatus = "destroying"
	V3_HEALTHY    V3ClusterStatus = "healthy"
	V3_DEGRADED   V3ClusterStatus = "degraded"
)

var allowedV3ClusterStatusEnumValues = []V3ClusterStatus{
	"draft",
	"deploying",
	"destroying",
	"healthy",
	"degraded",
}

func (v *V3ClusterStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V3ClusterStatus(value)
	for _, existing := range allowedV3ClusterStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V3ClusterStatus", value)
}

// NewV3ClusterStatusFromValue returns a pointer to a valid V3ClusterStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV3ClusterStatusFromValue(v string) (*V3ClusterStatus, error) {
	ev := V3ClusterStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V3ClusterStatus: valid values are %v", v, allowedV3ClusterStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V3ClusterStatus) IsValid() bool {
	for _, existing := range allowedV3ClusterStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v3ClusterStatus value
func (v V3ClusterStatus) Ptr() *V3ClusterStatus {
	return &v
}

type NullableV3ClusterStatus struct {
	value *V3ClusterStatus
	isSet bool
}

func (v NullableV3ClusterStatus) Get() *V3ClusterStatus {
	return v.value
}

func (v *NullableV3ClusterStatus) Set(val *V3ClusterStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableV3ClusterStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableV3ClusterStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV3ClusterStatus(val *V3ClusterStatus) *NullableV3ClusterStatus {
	return &NullableV3ClusterStatus{value: val, isSet: true}
}

func (v NullableV3ClusterStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV3ClusterStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
