/*
Couchbase Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// Couchbase, Inc. licenses this to you under the Apache License, Version 2.0 (the “License”);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at https://www.apache.org/licenses/LICENSE-2.0.

// Unless required by applicable law or agreed to in writing, software distributed under the License
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and limitations under the License.

package couchbasecapella

import (
	"encoding/json"
)

// ClusterStatusResponse struct for ClusterStatusResponse
type ClusterStatusResponse struct {
	Status ClusterStatus `json:"status"`
}

// NewClusterStatusResponse instantiates a new ClusterStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterStatusResponse(status ClusterStatus) *ClusterStatusResponse {
	this := ClusterStatusResponse{}
	this.Status = status
	return &this
}

// NewClusterStatusResponseWithDefaults instantiates a new ClusterStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterStatusResponseWithDefaults() *ClusterStatusResponse {
	this := ClusterStatusResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *ClusterStatusResponse) GetStatus() ClusterStatus {
	if o == nil {
		var ret ClusterStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ClusterStatusResponse) GetStatusOk() (*ClusterStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ClusterStatusResponse) SetStatus(v ClusterStatus) {
	o.Status = v
}

func (o ClusterStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableClusterStatusResponse struct {
	value *ClusterStatusResponse
	isSet bool
}

func (v NullableClusterStatusResponse) Get() *ClusterStatusResponse {
	return v.value
}

func (v *NullableClusterStatusResponse) Set(val *ClusterStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterStatusResponse(val *ClusterStatusResponse) *NullableClusterStatusResponse {
	return &NullableClusterStatusResponse{value: val, isSet: true}
}

func (v NullableClusterStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
